services:
  db:
    image: mysql:8.0
    container_name: simposio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simposio_db
    ports:
      - "3307:3336"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: . 
    container_name: simposio_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: simposio_db
    volumes:
    - .:/usr/src/app            
    - /usr/src/app/node_modules 
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
